import Zeta5.Integrals5Base

/-! # (5.10): the outer integral (generated by gen/gen_outer.py) -/

open MeasureTheory Set Finset
set_option linter.unusedSimpArgs false
set_option linter.deprecated false
noncomputable section
namespace Zeta5
open I5

lemma sum5 (h : ℕ → ℝ) : ∑ j ∈ Finset.Icc (1 : ℕ) 5, h j = h 1 + h 2 + h 3 + h 4 + h 5 := by
  rw [show Finset.Icc (1 : ℕ) 5 = {1, 2, 3, 4, 5} from rfl]; simp [Finset.sum_insert]; ring

lemma outer_piece_0 : IntervalIntegrable Lim.outerIntegrand volume (1 / 3 : ℝ) (43 / 120 : ℝ) ∧
    ∫ y in (1 / 3 : ℝ)..(43 / 120 : ℝ), Lim.outerIntegrand y =
      ((279 / 40 : ℝ) * (43 / 120 : ℝ) + (-9 : ℝ) * (43 / 120 : ℝ) ^ 2 / 2 + 0 * (43 / 120 : ℝ) ^ 3 / 3) -
      ((279 / 40 : ℝ) * (1 / 3 : ℝ) + (-9 : ℝ) * (1 / 3 : ℝ) ^ 2 / 2 + 0 * (1 / 3 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 2 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_1 : IntervalIntegrable Lim.outerIntegrand volume (43 / 120 : ℝ) (37 / 100 : ℝ) ∧
    ∫ y in (43 / 120 : ℝ)..(37 / 100 : ℝ), Lim.outerIntegrand y =
      ((451 / 40 : ℝ) * (37 / 100 : ℝ) + (-21 : ℝ) * (37 / 100 : ℝ) ^ 2 / 2 + 0 * (37 / 100 : ℝ) ^ 3 / 3) -
      ((451 / 40 : ℝ) * (43 / 120 : ℝ) + (-21 : ℝ) * (43 / 120 : ℝ) ^ 2 / 2 + 0 * (43 / 120 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 2 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_2 : IntervalIntegrable Lim.outerIntegrand volume (37 / 100 : ℝ) (13 / 30 : ℝ) ∧
    ∫ y in (37 / 100 : ℝ)..(13 / 30 : ℝ), Lim.outerIntegrand y =
      ((377 / 40 : ℝ) * (13 / 30 : ℝ) + (-16 : ℝ) * (13 / 30 : ℝ) ^ 2 / 2 + 0 * (13 / 30 : ℝ) ^ 3 / 3) -
      ((377 / 40 : ℝ) * (37 / 100 : ℝ) + (-16 : ℝ) * (37 / 100 : ℝ) ^ 2 / 2 + 0 * (37 / 100 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 2 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_3 : IntervalIntegrable Lim.outerIntegrand volume (13 / 30 : ℝ) (37 / 80 : ℝ) ∧
    ∫ y in (13 / 30 : ℝ)..(37 / 80 : ℝ), Lim.outerIntegrand y =
      ((429 / 40 : ℝ) * (37 / 80 : ℝ) + (-19 : ℝ) * (37 / 80 : ℝ) ^ 2 / 2 + 0 * (37 / 80 : ℝ) ^ 3 / 3) -
      ((429 / 40 : ℝ) * (13 / 30 : ℝ) + (-19 : ℝ) * (13 / 30 : ℝ) ^ 2 / 2 + 0 * (13 / 30 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 2 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_4 : IntervalIntegrable Lim.outerIntegrand volume (37 / 80 : ℝ) (1 / 2 : ℝ) ∧
    ∫ y in (37 / 80 : ℝ)..(1 / 2 : ℝ), Lim.outerIntegrand y =
      ((17 / 4 : ℝ) * (1 / 2 : ℝ) + (-5 : ℝ) * (1 / 2 : ℝ) ^ 2 / 2 + 0 * (1 / 2 : ℝ) ^ 3 / 3) -
      ((17 / 4 : ℝ) * (37 / 80 : ℝ) + (-5 : ℝ) * (37 / 80 : ℝ) ^ 2 / 2 + 0 * (37 / 80 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 2 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_5 : IntervalIntegrable Lim.outerIntegrand volume (1 / 2 : ℝ) (43 / 80 : ℝ) ∧
    ∫ y in (1 / 2 : ℝ)..(43 / 80 : ℝ), Lim.outerIntegrand y =
      ((51 / 10 : ℝ) * (43 / 80 : ℝ) + (-3 : ℝ) * (43 / 80 : ℝ) ^ 2 / 2 + 0 * (43 / 80 : ℝ) ^ 3 / 3) -
      ((51 / 10 : ℝ) * (1 / 2 : ℝ) + (-3 : ℝ) * (1 / 2 : ℝ) ^ 2 / 2 + 0 * (1 / 2 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 1 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_6 : IntervalIntegrable Lim.outerIntegrand volume (43 / 80 : ℝ) (37 / 60 : ℝ) ∧
    ∫ y in (43 / 80 : ℝ)..(37 / 60 : ℝ), Lim.outerIntegrand y =
      ((231 / 20 : ℝ) * (37 / 60 : ℝ) + (-15 : ℝ) * (37 / 60 : ℝ) ^ 2 / 2 + 0 * (37 / 60 : ℝ) ^ 3 / 3) -
      ((231 / 20 : ℝ) * (43 / 80 : ℝ) + (-15 : ℝ) * (43 / 80 : ℝ) ^ 2 / 2 + 0 * (43 / 80 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 1 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_7 : IntervalIntegrable Lim.outerIntegrand volume (37 / 60 : ℝ) (13 / 20 : ℝ) ∧
    ∫ y in (37 / 60 : ℝ)..(13 / 20 : ℝ), Lim.outerIntegrand y =
      ((97 / 10 : ℝ) * (13 / 20 : ℝ) + (-12 : ℝ) * (13 / 20 : ℝ) ^ 2 / 2 + 0 * (13 / 20 : ℝ) ^ 3 / 3) -
      ((97 / 10 : ℝ) * (37 / 60 : ℝ) + (-12 : ℝ) * (37 / 60 : ℝ) ^ 2 / 2 + 0 * (37 / 60 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 1 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_8 : IntervalIntegrable Lim.outerIntegrand volume (13 / 20 : ℝ) (2 / 3 : ℝ) ∧
    ∫ y in (13 / 20 : ℝ)..(2 / 3 : ℝ), Lim.outerIntegrand y =
      ((42 / 5 : ℝ) * (2 / 3 : ℝ) + (-10 : ℝ) * (2 / 3 : ℝ) ^ 2 / 2 + 0 * (2 / 3 : ℝ) ^ 3 / 3) -
      ((42 / 5 : ℝ) * (13 / 20 : ℝ) + (-10 : ℝ) * (13 / 20 : ℝ) ^ 2 / 2 + 0 * (13 / 20 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 1 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_9 : IntervalIntegrable Lim.outerIntegrand volume (2 / 3 : ℝ) (83 / 120 : ℝ) ∧
    ∫ y in (2 / 3 : ℝ)..(83 / 120 : ℝ), Lim.outerIntegrand y =
      ((42 / 5 : ℝ) * (83 / 120 : ℝ) + (-10 : ℝ) * (83 / 120 : ℝ) ^ 2 / 2 + 0 * (83 / 120 : ℝ) ^ 3 / 3) -
      ((42 / 5 : ℝ) * (2 / 3 : ℝ) + (-10 : ℝ) * (2 / 3 : ℝ) ^ 2 / 2 + 0 * (2 / 3 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 1 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_10 : IntervalIntegrable Lim.outerIntegrand volume (83 / 120 : ℝ) (23 / 30 : ℝ) ∧
    ∫ y in (83 / 120 : ℝ)..(23 / 30 : ℝ), Lim.outerIntegrand y =
      ((42 / 5 : ℝ) * (23 / 30 : ℝ) + (-10 : ℝ) * (23 / 30 : ℝ) ^ 2 / 2 + 0 * (23 / 30 : ℝ) ^ 3 / 3) -
      ((42 / 5 : ℝ) * (83 / 120 : ℝ) + (-10 : ℝ) * (83 / 120 : ℝ) ^ 2 / 2 + 0 * (83 / 120 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 1 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_11 : IntervalIntegrable Lim.outerIntegrand volume (23 / 30 : ℝ) (37 / 40 : ℝ) ∧
    ∫ y in (23 / 30 : ℝ)..(37 / 40 : ℝ), Lim.outerIntegrand y =
      ((42 / 5 : ℝ) * (37 / 40 : ℝ) + (-10 : ℝ) * (37 / 40 : ℝ) ^ 2 / 2 + 0 * (37 / 40 : ℝ) ^ 3 / 3) -
      ((42 / 5 : ℝ) * (23 / 30 : ℝ) + (-10 : ℝ) * (23 / 30 : ℝ) ^ 2 / 2 + 0 * (23 / 30 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 1 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_12 : IntervalIntegrable Lim.outerIntegrand volume (37 / 40 : ℝ) (1 : ℝ) ∧
    ∫ y in (37 / 40 : ℝ)..(1 : ℝ), Lim.outerIntegrand y =
      ((1 : ℝ) * (1 : ℝ) + (-2 : ℝ) * (1 : ℝ) ^ 2 / 2 + 0 * (1 : ℝ) ^ 3 / 3) -
      ((1 : ℝ) * (37 / 40 : ℝ) + (-2 : ℝ) * (37 / 40 : ℝ) ^ 2 / 2 + 0 * (37 / 40 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 1 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_13 : IntervalIntegrable Lim.outerIntegrand volume (1 : ℝ) (41 / 40 : ℝ) ∧
    ∫ y in (1 : ℝ)..(41 / 40 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (41 / 40 : ℝ) + (-1 : ℝ) * (41 / 40 : ℝ) ^ 2 / 2 + 0 * (41 / 40 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (1 : ℝ) + (-1 : ℝ) * (1 : ℝ) ^ 2 / 2 + 0 * (1 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_14 : IntervalIntegrable Lim.outerIntegrand volume (41 / 40 : ℝ) (83 / 80 : ℝ) ∧
    ∫ y in (41 / 40 : ℝ)..(83 / 80 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (83 / 80 : ℝ) + (-1 : ℝ) * (83 / 80 : ℝ) ^ 2 / 2 + 0 * (83 / 80 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (41 / 40 : ℝ) + (-1 : ℝ) * (41 / 40 : ℝ) ^ 2 / 2 + 0 * (41 / 40 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_15 : IntervalIntegrable Lim.outerIntegrand volume (83 / 80 : ℝ) (43 / 40 : ℝ) ∧
    ∫ y in (83 / 80 : ℝ)..(43 / 40 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (43 / 40 : ℝ) + (-1 : ℝ) * (43 / 40 : ℝ) ^ 2 / 2 + 0 * (43 / 40 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (83 / 80 : ℝ) + (-1 : ℝ) * (83 / 80 : ℝ) ^ 2 / 2 + 0 * (83 / 80 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_16 : IntervalIntegrable Lim.outerIntegrand volume (43 / 40 : ℝ) (11 / 10 : ℝ) ∧
    ∫ y in (43 / 40 : ℝ)..(11 / 10 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (11 / 10 : ℝ) + (-1 : ℝ) * (11 / 10 : ℝ) ^ 2 / 2 + 0 * (11 / 10 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (43 / 40 : ℝ) + (-1 : ℝ) * (43 / 40 : ℝ) ^ 2 / 2 + 0 * (43 / 40 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_17 : IntervalIntegrable Lim.outerIntegrand volume (11 / 10 : ℝ) (23 / 20 : ℝ) ∧
    ∫ y in (11 / 10 : ℝ)..(23 / 20 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (23 / 20 : ℝ) + (-1 : ℝ) * (23 / 20 : ℝ) ^ 2 / 2 + 0 * (23 / 20 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (11 / 10 : ℝ) + (-1 : ℝ) * (11 / 10 : ℝ) ^ 2 / 2 + 0 * (11 / 10 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_18 : IntervalIntegrable Lim.outerIntegrand volume (23 / 20 : ℝ) (13 / 10 : ℝ) ∧
    ∫ y in (23 / 20 : ℝ)..(13 / 10 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (13 / 10 : ℝ) + (-1 : ℝ) * (13 / 10 : ℝ) ^ 2 / 2 + 0 * (13 / 10 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (23 / 20 : ℝ) + (-1 : ℝ) * (23 / 20 : ℝ) ^ 2 / 2 + 0 * (23 / 20 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_19 : IntervalIntegrable Lim.outerIntegrand volume (13 / 10 : ℝ) (4 / 3 : ℝ) ∧
    ∫ y in (13 / 10 : ℝ)..(4 / 3 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (4 / 3 : ℝ) + (-1 : ℝ) * (4 / 3 : ℝ) ^ 2 / 2 + 0 * (4 / 3 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (13 / 10 : ℝ) + (-1 : ℝ) * (13 / 10 : ℝ) ^ 2 / 2 + 0 * (13 / 10 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_20 : IntervalIntegrable Lim.outerIntegrand volume (4 / 3 : ℝ) (163 / 120 : ℝ) ∧
    ∫ y in (4 / 3 : ℝ)..(163 / 120 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (163 / 120 : ℝ) + (-1 : ℝ) * (163 / 120 : ℝ) ^ 2 / 2 + 0 * (163 / 120 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (4 / 3 : ℝ) + (-1 : ℝ) * (4 / 3 : ℝ) ^ 2 / 2 + 0 * (4 / 3 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_21 : IntervalIntegrable Lim.outerIntegrand volume (163 / 120 : ℝ) (43 / 30 : ℝ) ∧
    ∫ y in (163 / 120 : ℝ)..(43 / 30 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (43 / 30 : ℝ) + (-1 : ℝ) * (43 / 30 : ℝ) ^ 2 / 2 + 0 * (43 / 30 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (163 / 120 : ℝ) + (-1 : ℝ) * (163 / 120 : ℝ) ^ 2 / 2 + 0 * (163 / 120 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_22 : IntervalIntegrable Lim.outerIntegrand volume (43 / 30 : ℝ) (3 / 2 : ℝ) ∧
    ∫ y in (43 / 30 : ℝ)..(3 / 2 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (3 / 2 : ℝ) + (-1 : ℝ) * (3 / 2 : ℝ) ^ 2 / 2 + 0 * (3 / 2 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (43 / 30 : ℝ) + (-1 : ℝ) * (43 / 30 : ℝ) ^ 2 / 2 + 0 * (43 / 30 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_23 : IntervalIntegrable Lim.outerIntegrand volume (3 / 2 : ℝ) (123 / 80 : ℝ) ∧
    ∫ y in (3 / 2 : ℝ)..(123 / 80 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (123 / 80 : ℝ) + (-1 : ℝ) * (123 / 80 : ℝ) ^ 2 / 2 + 0 * (123 / 80 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (3 / 2 : ℝ) + (-1 : ℝ) * (3 / 2 : ℝ) ^ 2 / 2 + 0 * (3 / 2 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_24 : IntervalIntegrable Lim.outerIntegrand volume (123 / 80 : ℝ) (33 / 20 : ℝ) ∧
    ∫ y in (123 / 80 : ℝ)..(33 / 20 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (33 / 20 : ℝ) + (-1 : ℝ) * (33 / 20 : ℝ) ^ 2 / 2 + 0 * (33 / 20 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (123 / 80 : ℝ) + (-1 : ℝ) * (123 / 80 : ℝ) ^ 2 / 2 + 0 * (123 / 80 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_25 : IntervalIntegrable Lim.outerIntegrand volume (33 / 20 : ℝ) (5 / 3 : ℝ) ∧
    ∫ y in (33 / 20 : ℝ)..(5 / 3 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (5 / 3 : ℝ) + (-1 : ℝ) * (5 / 3 : ℝ) ^ 2 / 2 + 0 * (5 / 3 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (33 / 20 : ℝ) + (-1 : ℝ) * (33 / 20 : ℝ) ^ 2 / 2 + 0 * (33 / 20 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_26 : IntervalIntegrable Lim.outerIntegrand volume (5 / 3 : ℝ) (203 / 120 : ℝ) ∧
    ∫ y in (5 / 3 : ℝ)..(203 / 120 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (203 / 120 : ℝ) + (-1 : ℝ) * (203 / 120 : ℝ) ^ 2 / 2 + 0 * (203 / 120 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (5 / 3 : ℝ) + (-1 : ℝ) * (5 / 3 : ℝ) ^ 2 / 2 + 0 * (5 / 3 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_27 : IntervalIntegrable Lim.outerIntegrand volume (203 / 120 : ℝ) (53 / 30 : ℝ) ∧
    ∫ y in (203 / 120 : ℝ)..(53 / 30 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (53 / 30 : ℝ) + (-1 : ℝ) * (53 / 30 : ℝ) ^ 2 / 2 + 0 * (53 / 30 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (203 / 120 : ℝ) + (-1 : ℝ) * (203 / 120 : ℝ) ^ 2 / 2 + 0 * (203 / 120 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

lemma outer_piece_28 : IntervalIntegrable Lim.outerIntegrand volume (53 / 30 : ℝ) (37 / 20 : ℝ) ∧
    ∫ y in (53 / 30 : ℝ)..(37 / 20 : ℝ), Lim.outerIntegrand y =
      ((37 / 20 : ℝ) * (37 / 20 : ℝ) + (-1 : ℝ) * (37 / 20 : ℝ) ^ 2 / 2 + 0 * (37 / 20 : ℝ) ^ 3 / 3) -
      ((37 / 20 : ℝ) * (53 / 30 : ℝ) + (-1 : ℝ) * (53 / 30 : ℝ) ^ 2 / 2 + 0 * (53 / 30 : ℝ) ^ 3 / 3) := by
  refine piece_quad' (by norm_num) _ _ _ fun y hy => ?_
  obtain ⟨h1, h2⟩ := hy
  simp only [Lim.outerIntegrand, sum5, Nat.cast_ofNat, Nat.cast_one, Lim.R0, Lim.dfun, Lim.pos,
    Lim.α, Lim.lam]
  rw [floor_inv_eq 0 (by norm_num at h1 h2 ⊢; linarith) (by push_cast; nlinarith)
    (by push_cast; nlinarith)]
  simp (disch := dsch) only [if_pos, if_neg, max_eq_left, max_eq_right, min_eq_left, min_eq_right]
  push_cast
  ring

theorem integral_5_10' : ∫ y in (1 / 3 : ℝ)..(2 * Lim.lam), Lim.outerIntegrand y = (Iout : ℝ) := by
  have h := (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain outer_piece_0 outer_piece_1) outer_piece_2) outer_piece_3) outer_piece_4) outer_piece_5) outer_piece_6) outer_piece_7) outer_piece_8) outer_piece_9) outer_piece_10) outer_piece_11) outer_piece_12) outer_piece_13) outer_piece_14) outer_piece_15) outer_piece_16) outer_piece_17) outer_piece_18) outer_piece_19) outer_piece_20) outer_piece_21) outer_piece_22) outer_piece_23) outer_piece_24) outer_piece_25) outer_piece_26) outer_piece_27) outer_piece_28)
  rw [show (2 * Lim.lam : ℝ) = (37 / 20 : ℝ) by norm_num [Lim.lam], h.2]
  norm_num [Iout]

end Zeta5
